let model,view='admissions';const panel=document.querySelector('#demo-panel'),notice=document.querySelector('#demo-status');
function reset(){model={enrolled:false,group:'Qaidah Foundations',attendance:'Not recorded',homework:false,points:85};view='admissions';render();notice.textContent='Demonstration reset.';}
function render(){document.querySelectorAll('[data-view]').forEach(b=>{b.setAttribute('aria-selected',String(b.dataset.view===view));b.tabIndex=b.dataset.view===view?0:-1});panel.setAttribute('aria-labelledby','tab-'+view);
if(view==='admissions')panel.innerHTML=`<div class="demo-toolbar"><h2>Applications</h2><span class="tag gold">${model.enrolled?'ENROLLED':'1 NEW APPLICATION'}</span></div><div class="demo-card"><h3>Yusuf Ahmed</h3><p>Age 8 · Parent: Amina Ahmed</p><p>Interested in learning to read the Qur’an. Beginner, available after school.</p><label>Choose a class<select id="demo-class" ${model.enrolled?'disabled':''}><option ${model.group==='Qaidah Foundations'?'selected':''}>Qaidah Foundations</option><option ${model.group==='Qur’an Reading'?'selected':''}>Qur’an Reading</option></select></label><p class="micro">The live workflow includes checking details and setting up the student and parent accounts.</p><button class="button" id="enrol" ${model.enrolled?'disabled':''}>${model.enrolled?'✓ Enrolled in '+model.group:'Enrol student in this class'}</button></div>`;
if(view==='class')panel.innerHTML=`<div class="demo-toolbar"><h2>${model.group}</h2><span class="tag gold">TEACHER VIEW</span></div>${!model.enrolled?'<p class="demo-notice">Start with Enrolment to add Yusuf to this class.</p>':`<div class="demo-row"><span><strong>Yusuf Ahmed</strong><br>Attendance</span><select id="attendance" aria-label="Yusuf’s attendance">${['Not recorded','Present','Late','Absent'].map(s=>'<option '+(model.attendance===s?'selected':'')+'>'+s+'</option>').join('')}</select></div><div class="demo-row"><span><strong>Weekly practice</strong><br>Practise joined letters for five minutes daily.</span><button class="button" id="homework">${model.homework?'✓ Homework assigned':'Assign homework'}</button></div><div class="demo-row"><span><strong>Effort & improvement</strong><br>${model.points} points</span><button class="button" id="points">Award +5 points</button></div>`}`;
if(view==='parent')panel.innerHTML=`<div class="demo-toolbar"><h2>Yusuf’s learning</h2><span class="tag gold">PARENT VIEW</span></div>${!model.enrolled?'<p>Yusuf’s application is awaiting enrolment. Complete step 1 to see his class here.</p>':`<div class="demo-grid"><div class="demo-card"><h3>${model.group}</h3><p>Monday · 16:30–17:30<br>Teaching room</p><p><strong>Attendance:</strong> ${model.attendance}</p></div><div class="demo-card"><h3>${model.points} points</h3><p>Recognising effort and improvement.</p></div></div><div class="demo-card"><h3>Practice for this week</h3><p>${model.homework?'Practise joined letters for five minutes each day. Read slowly and repeat the letters discussed with your teacher.':'No homework assigned yet. Try assigning some in the Teaching step.'}</p></div>`}`;
}
document.querySelectorAll('[data-view]').forEach(b=>{b.onclick=()=>{view=b.dataset.view;render();notice.textContent=''};b.onkeydown=e=>{const buttons=[...document.querySelectorAll('[data-view]')];let i=buttons.indexOf(b);if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();i=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;buttons[i].click();buttons[i].focus()}}});
panel.addEventListener('click',e=>{if(e.target.id==='enrol'){model.group=document.querySelector('#demo-class').value;model.enrolled=true;notice.textContent='Yusuf is enrolled. Open Teaching to record his lesson.';render()}if(e.target.id==='homework'){model.homework=true;notice.textContent='Homework assigned. It is now visible in Parent view.';render()}if(e.target.id==='points'){model.points+=5;notice.textContent='5 points awarded. New total: '+model.points+'.';render()}});panel.addEventListener('change',e=>{if(e.target.id==='attendance'){model.attendance=e.target.value;notice.textContent='Attendance recorded as '+model.attendance+'.'}});document.querySelector('#reset-demo').onclick=reset;reset();notice.textContent='';
